### ISSUE TITLE
jack should support chai.should syntax

### ISSUE THREAD

**Issue by davidshen84** [vesln/jack#6]
I tried

```
MyObj.foo.should.be.called.once
```

And I got

```
TypeError: Cannot read property '__stub' of undefined
```

But if I doo

```
Blog.spy('update').it.should_be.called.once;
```

The code works correctly as expected. I guess the _should_ syntax is **not** supported?

**Comment by vesln** [comment]
Unfortunately, Jack is a bit out of sync with chai.js. It's a top priority on my list to release "jack reloaded" and move it to the Chai.js organization, but this will take some time, since I plan to introduce a brand new architecture. Until then I'd be more than happy to merge any pull request that fixes existing issues. Thank you.
